import { Metadata } from "next";
import { JobTypes, Promotion, Services, Welcome } from "./components";
import Carousel from "./components/Carousel";
import React from "react";

export const metadata: Metadata = {
  title: "Fiverr - Freelancer",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Carousel />
      <Services />
      <Promotion />
      <JobTypes />
      <Welcome />
    </div>
  );
}
